#
# Site settings
#
remote_theme: LeakyAbstractions/pretty-docs
url: https://RoM-EternalPov.github.io
baseurl: /
title: &site_title RoM Eternal PoV
description: &site_description Guides Collection about Ragnarok Mobil Eternal Love (EU)
branding:
  icon:
    type: fa
    name: fa-unlink
  highlight: RoM
  bold: Eternal PoV
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: La Z0ne
  copyright:
    notice: Together, we hit harder!
    author: "S0m3b0dy and S0m30n3 else"

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
