#
# Site settings
#
remote_theme: LeakyAbstractions/pretty-docs
url: https://RoM-EternalPov.github.io
baseurl: /
title: &site_title RoM Eternal PoV
description: &site_description Guides Collection about Ragnarok Mobil Eternal Love (EU)
favicon: "/assets/images/favicon.ico"
favicon16x16: "/assets/images/favicon-16x16.png" 
favicon32x32: "/assets/images/favicon-32x32.png"
android_chrome192x192: "/assets/images/android-chrome-192x192.png" 
android_chrome512x512: "/assets/images/android-chrome-512x512.png" 
apple_touch_icon: "/assets/images/apple-touch-icon.png" 
branding:
  icon:
    type: fa
    name: fa-unlink
  highlight: RoM
  bold: Eternal PoV
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: La Z0ne
  copyright:
    notice: Together, we hit harder!
    author: "S0m3b0dy and S0m30n3 else"

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
